### ISSUE TITLE
May I know how to use it?

### ISSUE THREAD

**Issue by winsonet** [lanly-dev/VSCode-LMPTM#1]
can't find any menus or commands? :(

**Comment by lanly-dev** [comment]
Sorry for not including the detail for how to use this.
When you install the extension, there is a little button 'Launch 🚀' on the bottom right corner in VS Code.
![1](https://user-images.githubusercontent.com/14204732/64916591-f5958980-d734-11e9-99aa-04bf72a623c0.PNG)
This button would bring up a Chrome or Chromium browser (I haven't test it with Chromium yet, I'm not sure if it would work). Note that, Chrome/Chromium needs to be installed first.
![2](https://user-images.githubusercontent.com/14204732/64916623-a69c2400-d735-11e9-93c4-18c61ab49888.PNG)
You will see a button on the bottom right in the browser. You have to click it to let the extension know which tab that you want to control. By clicking it, you will see the playback control buttons show up in VS Code a long with the tab title.
![3](https://user-images.githubusercontent.com/14204732/64916642-f844ae80-d735-11e9-9ec1-1ab24c737620.PNG)
Enjoy!

**Comment by winsonet** [comment]
oh~~thanks!

**Comment by Xart3misX** [comment]
how do i change the browser (mozzila firefox)

**Comment by lanly-dev** [comment]
Firefox isn't base on on Chromium so it won't work.

**Comment by RegenJacob** [comment]
can i change the browser to brave?

**Comment by lanly-dev** [comment]
@RegenJacob Yes, you need to edit on these 2 settings in order to use Brave browser:

- `lmptm.browserPath`: Specify the preferred browser executable file path.

- `lmptm.ignoreDisableSync`: Ignore --disable-sync, this option is specifically for Brave browser.

**Comment by educbraga** [comment]
Hi! Is it possible to change it to Non-Incognito mode?  I'm using Google Chrome :)

**Comment by lanly-dev** [comment]
@educbraga there is a setting to turn it off:

- `lmptm.incognitoMode:` Specify whether to launch browser in incognito/private mode.

**Comment by night05fury** [comment]
can i use it on microsoft edge??

**Comment by lanly-dev** [comment]
@night05fury yes, for the new Edge that based on Chromium.

**Comment by DroidZed** [comment]
What if I wanted to close the tab ? Can I have it continue playing the music after I linked it with spotify ?

**Comment by lanly-dev** [comment]
@DroidZed No, it doesn't work like that. You could minimize the browser though.

**Comment by DroidZed** [comment]
Yes, well I don't mind that. Thanks for making this plugin ! It's the only one that works and accepts free accounts ^^

**Comment by gshanbhag525** [comment]
@lanly-dev how can i pause song in the vscode....how can i change the mapping of keyboard shortcuts...i checked in settings.json and there is no setting related to it.

**Comment by lanly-dev** [comment]
Alt+Windows+DownArrow to toggle play/pause.
For changing the key mapping, take a look at https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by jwalkerinterpres** [comment]
Why would you link to an issues page ... when you could just explain how to use the plug-in right where you ask the question?

**Comment by lanly-dev** [comment]
> Why would you link to an issues page ... when you could just explain how to use the plug-in right where you ask the question?

hm.... maybe I didn't want to write more back then?
