### ISSUE TITLE
The Pick button is gone on the YouTube and YouTube Music pages

### ISSUE THREAD

**Issue by mattzgg** [lanly-dev/VSCode-LMPTM#15]
After clicking the **Launch** button, there is no **Pick** button on the YouTube and YouTube Music pages.

The Runtime Status of the extension shows the following error:

Evaluation failed: TypeError: Failed to set the 'text' property on 'HTMLScriptElement': This document requires 'TrustedScript' assignment. at n (puppeteer_evaluation_script:1:94)

**Comment by mattzgg** [comment]
According to this article [Adding Trusted Types to YouTube](https://developer.chrome.com/blog/trusted-types-on-youtube), the Trusted Types was introduced to YouTube. So the injection of the script into the page when the page is being loaded violates the CSP rules.

**Comment by mattzgg** [comment]
It seems there is no solution at the moment. I need to use this extension so I cloned the repo and made a change to the `Browser.launchPages` method to make pages bypass CSP when they're created. It could not be the perfect solution to the issue because I haven't delved into the code. So use the change as a workraound now. If you are waiting for the solution you can use the extension that I built below as a workaround.
[letmeplaythemusic-2.1.0.vsix.zip](https://github.com/user-attachments/files/17001964/letmeplaythemusic-2.1.0.vsix.zip)

Unzip the file and install the extension from the vsix file.

**Comment by lanly-dev** [comment]
Great insights, I noticed couple days ago about this issue, too - I tried the bypass CSP and it does work like you said. I was going to test it out more in Chrome - I was using Edge so I thought it could be Edge's problem solely but now I know it from Youtube thanks to your info. I will update sometime after I set up my VM to test it out more.

**Comment by mattzgg** [comment]
The timing to call `Page.setByPassCSP` is important according to remarks from [Puppeteer API Doc](https://pptr.dev/api/puppeteer.page.setbypasscsp). I put it in the Browser.js code like this
`       
        const pg = await this.newPage()
        pg.setBypassCSP(true)
`
and it works.

Thank you for your attention. Your work is great and helps us follow tutorials on YouTube easily.

**Comment by lanly-dev** [comment]
I updated the extension, hope it helps.
