### ISSUE TITLE
Cannot properly play from Chromium-based browsers

### ISSUE THREAD

**Issue by cubuzz** [lanly-dev/VSCode-LMPTM#3]
(Disclaimer: I'm using Brave, a custom implementation of Chromium that's symlinked AS chrome.)
I get the window up and running properly, but the extension does not recognize my YouTube playback. Same goes for SoundCloud. Couldn't try out Spotify cuz I don't have an account. Can you check that out, please?

**Comment by lanly-dev** [comment]
May I know which OS are you using?

**Comment by mritunjaymusale** [comment]
Mac OS
In it's current state it opens chrome but I would like it to use Brave Browser instead

**Comment by lanly-dev** [comment]
Now you can use it with Brave! Cheers!
![image](https://user-images.githubusercontent.com/14204732/71563449-9be76f80-2a44-11ea-93c7-c09439dfe9d4.png)

**Comment by mritunjaymusale** [comment]
On my desktop I use Linux Mint, I tried the custom path approach and set it to Brave I get this message:
![Screenshot from 2020-01-08 23-14-53](https://user-images.githubusercontent.com/25117230/72002162-e8b11e80-326c-11ea-984f-9097b8ad1892.png)

**Comment by lanly-dev** [comment]
I tried to debug it but it doesn't give much information:
```
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    readyState: 3,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _isServer: false,
    _redirects: 0,
    url: 'ws://127.0.0.1:42067/devtools/browser/6acf5785-34e3-4f9d-99b3-b47f46f01007',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'socket hang up',
  error: Error: socket hang up
      at connResetException (internal/errors.js:609:14)
      at Socket.socketOnEnd (_http_client.js:455:23)
      at Socket.emit (events.js:333:22)
      at endReadableNT (_stream_readable.js:1220:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  }
}
```
Brave browser never show up so the websocket get hang up.

A couple attempts that I tried:
- Update to latest Node|npm (its default was Node 8|npm 3 😨), and system packages don't work
- Tried install a bunch of similar packages (that I found in similar issues) doesn't work
- Brave nightly version doesn't work
- Different launch flag doesn't work, but pipe: true gives Target Closed error instead
- Puppeteer headless = true it works

Some similar issues that I found:
https://github.com/puppeteer/puppeteer/issues/2734
https://github.com/puppeteer/puppeteer/issues/3605
https://github.com/puppeteer/puppeteer/issues/2430

Since most of the similar issues mostly occur on either Centos and in Docker, and the extension <-> Brave works on more well-known OS - Ubuntu, Win, and macOS. Look like either Linux Mint has something missing/outdated packages or the Brave/puppeteer didn't test, therefore a bug, on Mint. Unfortunately, I can't figure out what is it. Sorry.

**Comment by lanly-dev** [comment]
This got fixed in 1.3.0, see https://github.com/lanly-dev/VSCode-LMPTM/issues/5

**Comment by amrsa1** [comment]
What was the solution ?  Im encountering the same issue

**Comment by lanly-dev** [comment]
@amrsa1 are you using Brave?

**Comment by amrsa1** [comment]
> @amrsa1 are you using Brave?

I have both browsers installed on my mac, brave is the default one

**Comment by lanly-dev** [comment]
There is a Brave setting that I removed for 3.0 - https://github.com/lanly-dev/VSCode-LMPTM/issues/5#issuecomment-583882280. Did you use/enable that in earlier version of LMPTM?

**Comment by amrsa1** [comment]
I dont have such option LMPTM

**Comment by lanly-dev** [comment]
@amrsa1 try to install earlier version of the extension, and enable that setting, if it works, I will put it back.

**Comment by amrsa1** [comment]
Sorry whats the name of the extention LMPTM there is no such one 
<img width="163" alt="Screenshot 2024-12-02 at 12 00 50" src="https://github.com/user-attachments/assets/c2e3cbe8-4b02-4abf-b1b6-6a31db1f50fb">

**Comment by lanly-dev** [comment]
are you talking about this specifically issue or how to connect this [VS code extension](https://marketplace.visualstudio.com/items?itemName=lanly-dev.letmeplaythemusic) with Brave Browser?
LMPTM == letmeplaythemusic

**Comment by amrsa1** [comment]
i just have the following basic script 

```
const puppeteer = require ("puppeteer");
(async () => {
  try {
	const browser = await puppeteer.launch({ headless: false });
	const page = await browser.newPage();
	await page.goto('https://google.com');
	await page.screenshot({ path: 'google.png' });
	await browser.close();
  } catch (err) {
	console.log(err);
  }
})();
```

It doesn't work due to the following issue:

```
ErrorEvent {
  [Symbol(kTarget)]: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: 'ws://127.0.0.1:50421/devtools/browser/2e404102-6b7d-480c-b81d-4cda28c9dfb8',
    _originalIpc: false,
    _originalSecure: false,
    _originalHostOrSocketPath: '127.0.0.1:50421',
    _req: null,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: Error: socket hang up
      at Socket.socketOnEnd (node:_http_client:530:25)
      at Socket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1698:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
    code: 'ECONNRESET'
  },
  [Symbol(kMessage)]: 'socket hang up'
}
```

**Comment by lanly-dev** [comment]
okay, got it, you are talking the issue not about this extension, there was [a flag setting](https://github.com/GoogleChrome/chrome-launcher/blob/d6be1f3250ef7ff7648ae58c4e92e48509bdbe7c/docs/chrome-flags-for-tools.md?plain=1#L110) that I found that if you put that in puppeteer like this:
```
puppeteer.launch({
  args,
  defaultViewport: null,
  executablePath: String(cPath),
  headless: false,
  ignoreDefaultArgs: `--disable-sync`
})
```
It worked on my case, which was a long time ago...
And I'm using `"puppeteer-core": "^13.0.0"` which is not actual full puppeteer, it is launching the browser that installed on the system from given the executable path, not the one from `puppeteer` downloaded.
