### ISSUE TITLE
LMTP not working in Ubuntu with chrome or brave

### ISSUE THREAD

**Issue by ManukrishnanP** [lanly-dev/VSCode-LMPTM#9]
I am using this extension in vs code preferably with chrome but when using with chrome stable the new window just comes up and goes away neither does it open the websites nor does it show controls in the bottom status bar of vs code but it says "running" though.

When using with brave, 
it opens brave with no website open in the default settings of brave but it is not connected to the extension and in vs code this error pops up

_Puppeteer was unable to kill the process which ran the browser binary.
This means that, on future Puppeteer launches, Puppeteer might not be able to launch the browser.
Please check your open processes and ensure that the browser processes that Puppeteer launched have been killed.
If you think this is a bug, please report it on the Puppeteer issue tracker.
Error cause: Error: kill EACCES
	at ChildProcess.kill (internal/child_process.js:492:26)
	at t.BrowserRunner.kill (/home/mk/.vscode/extensions/lanly-dev.letmeplaythemusic-1.4.0/dist/extension.js:3:104467)
	at k.launch (/home/mk/.vscode/extensions/lanly-dev.letmeplaythemusic-1.4.0/dist/extension.js:1:152158)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)_

**Comment by lanly-dev** [comment]
I plan to update this extension when I am able to. Also waiting on `https://github.com/berstend/puppeteer-extra/pull/303#` to be released so it could be quite some time. What is the OS that you are using it on?

**Comment by lanly-dev** [comment]
I am closing this since there is no response.
Please try again for the future release and see if it still has the same problem.
